### ISSUE TITLE
"Unsupported operation on macOS: Unable to call foreign function _ZNSt3__123__cxx_atomic_notify_oneEPVKv in atomic-wait crate" 

### ISSUE THREAD

**Issue by edneedham** [m-ou-se/atomic-wait#2]
Hey Mara,

I ran into this issue when doing the exercises in your awesome book. When running with 
`cargo test` there is occasionally a failed assertion, however every time the code is run with miri
it fails with the error in the title.

I have provided a link to the [Semaphore source code.](https://github.com/edneedham/a_and_l_exercises/blob/main/semaphore/src/lib.rs) 

System specs:
`Intel Quad-Core i7 X86-64`
`macOS Big Sur 11.6.8`

Rust version: 
`1.69.0`

Dependencies:
`atomic-wait = "1"`

Here is the relevant code:
```rust
//<snip>

impl<T> DerefMut for SemaphoreGuard<'_, T> {
    fn deref_mut(&mut self) -> &mut T {
        unsafe { &mut *self.semaphore.value.get() }
    }
}

impl<T> Semaphore<T> {

    //<snip>

    pub fn signal(&self) -> SemaphoreGuard<T> {
        SemaphoreGuard { semaphore: self }
    }

    //<snip>

}

impl<T> Drop for SemaphoreGuard<'_, T> {
    fn drop(&mut self) {
        // Add one back to the counter: a resource is released. 
        let _ = self.semaphore.counter.fetch_add(1, Ordering::Release);
        atomic_wait::wake_one(&self.semaphore.counter);
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;
    use std::thread;
    use super::*;
    #[test]
    fn basic() {
        let num_of_desks = 2;
        let resources = 60;
        let office = Arc::new(
            Semaphore::new(resources, number_of_desks)
        );
        let num_workers = 3;
        let num_updates_per_worker = 20;

        let mut handles = vec![];

        for _ in 0..num_workers {
            let office_clone = Arc::clone(&office);
            let handle = thread::spawn(move || {
                for _ in 0..num_updates_per_worker {
                    office_clone.wait();
                    let mut resources_guard = office_clone.signal();
                    *resources_guard -= 1;
                }
            });
            handles.push(handle);
        }
        for handle in handles {
            handle.join().unwrap();
        }

        let final_value_guard = office.signal();
        assert_eq!(*final_value_guard, 0);
    }
}
```
Running the code with miri enabled: 

`rustup component add --toolchain nightly miri`
`cargo +nightly miri test`

And this was the output:

<img width="719" alt="error_output" src="https://user-images.githubusercontent.com/44907964/234275586-065570df-db44-47c6-b608-26bfd2339eec.png">

**Comment by m-ou-se** [comment]
Miri simply doesn't support this operation on Mac. You could file a feature request for miri here: https://github.com/rust-lang/miri/issues

Miri has much more complete support for all kind of operations on Linux. The platform it emulates is independent of the platform it runs on, so you should be able to just add `--target x86_64-unknown-linux-gnu` to make use of Miri's Linux support, even if you're on Mac or Windows.

**Comment by edneedham** [comment]
Thank you for getting back to me so quickly, that has solved the issue. I now get to see my data race. :smile:
